### ISSUE TITLE
Installation/Command Lines 

### ISSUE THREAD

**Issue by jenniferlu717** [DiltheyLab/MetaMaps#1]
Just to let you know, running `make metamaps` does not work. `make install` alone does, but the executable isn't `./metamaps`, it makes the executable of `mashmap`

**Comment by alegione** [comment]
I had this issue too, saw that inside the make file was 'install: mashmap' too
Otherwise, when using 'make metamaps' the error "make: *** No rule to make target 'metamaps'.  Stop." arises

**Comment by AlexanderDilthey** [comment]
Sorry about this! I hadn't updated the makefile. This is fixed now!
