### ISSUE TITLE
Metamaps cant find boost files

### ISSUE THREAD

**Issue by mbhall88** [DiltheyLab/MetaMaps#12]
I am having some trouble building metamaps. It seems to be struggling to find some files that definitely exist. I will provide the full list of commands I ran (I am doing this inside a container).

```sh
    #============================================
    # INSTALL ZLIB
    #============================================
    VERSION="1.2.11"
    wget http://www.zlib.net/zlib-"$VERSION".tar.gz -O - | tar xzf -
    cd zlib-"$VERSION"
    ./configure --prefix=/usr/local
    make
    make install
    cd ..

    #============================================
    # INSTALL BOOST 
    #============================================
    wget https://sourceforge.net/projects/boost/files/boost/1.62.0/boost_1_62_0.tar.gz -O - | tar xzf -
    cd boost_1_62_0
    ./bootstrap.sh --prefix=/usr/local 
    ./b2 install
    cd ..

    #============================================
    # INSTALL METAMAPS 
    #============================================
    apt install -y autoconf
    URL=https://github.com/DiltheyLab/MetaMaps.git
    COMMIT="8eb0ddbeb630c01f808f6ca79c1a28a6c39df40c"
    git clone "$URL"
    cd MetaMaps || exit 1
    git checkout "$COMMIT"
    ./bootstrap.sh
    ./configure --with-boost=/usr/local
    make metamaps
```

Everything runs fine but when I got to execute the binary with `./metamaps` I get the following error

```
./metamaps: error while loading shared libraries: libboost_system.so.1.62.0: cannot open shared object file: No such file or directory
```

Running `find / -name libboost_system.so.1.62.0` gives
```
/usr/local/lib/libboost_system.so.1.62.0
```
which is where I told metamaps boost was located....

**Comment by AlexanderDilthey** [comment]
Most likely you need to add the directory that Boost is located in to the LD_LIBRARY_PATH environment variable.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by mbhall88** [comment]
Still getting the same problem...

**Comment by AlexanderDilthey** [comment]
Can you send me the complete contents of your LD_LIBRARY_PATH variable just prior to calling MetaMaps?

**Comment by mbhall88** [comment]
Ah, my apologies. I had been exporting `/usr/local` to `LD_LIBRARY_PATH`. Exporting `/usr/local/lib` fixed it and I can execute `metamaps` now.
