### ISSUE TITLE
meta::getTaxonIDsFromMappingsFile(std::string): Assertion `mappingsStream.is_open()' failed

### ISSUE THREAD

**Issue by Earwelen** [DiltheyLab/MetaMaps#16]
Hello,

I ran metamaps mapDirectly, and get the output.x files. I am not sure what to expect from this first step, but the .output file (without .1 or .x) is sometimes missing, and this seems a first issue discussed here: https://github.com/DiltheyLab/MetaMaps/issues/7#issuecomment-440191480

In the second step, i am getting the following error. Commands:
```
conda activate metamap-0.1
metamaps classify --threads 12 --DB /path/to/miniSeq+H --mappings /path/to/file/nanopore_file.metamaps_standard_output
```
Error:
```
metamaps: src/meta/fEM.h:1362: std::set<std::basic_string<char> > meta::getTaxonIDsFromMappingsFile(std::string): Assertion `mappingsStream.is_open()' failed.
/.../source_activate.sh: line 36: 213339 Aborted                 (core dumped) "$@"
```
Could you help on this issue ?
Thank you in advance,
Sylvain

**Comment by AlexanderDilthey** [comment]
Hi @Earwelen, could you post the full command you use for the mapping step?

**Comment by Earwelen** [comment]
Hi @AlexanderDilthey ,
If I remember the issue was the memory usage. Using qsub on a server, i specified a memory requirement but the usage was much more than the target max memory (something like 52GB while targeting for 30GB) and it generated errors. Not sure why, but the memory consumption was close to the double of the specified amount.
Thank you.

**Comment by AlexanderDilthey** [comment]
@Earwelen Thank you for getting back to us on this! Yes, this behavior is known and documented; but perhaps we have to increase the recommended factor between parameter value and available memory.
