### ISSUE TITLE
Informations on output needed

### ISSUE THREAD

**Issue by RxLoutre** [DiltheyLab/MetaMaps#2]
Hello !

Is it possible to have somewhere an example of an output file produced by metamaps ? Or does it already exist somwhere and I couldn't reach it ? I would like to know what does the output look like and how I could visualize it.

Thanks a lot !

Roxane

**Comment by AlexanderDilthey** [comment]
Hi!

Thank you for the good suggestion! I've added a corresponding section to the README file!

**Comment by RxLoutre** [comment]
Thanks a lot for adding it ! Do you have by any chance an example of a real file I could have an eye on ?

**Comment by AlexanderDilthey** [comment]
I'll produce one!

**Comment by AlexanderDilthey** [comment]
Here we go: https://github.com/DiltheyLab/MetaMaps/blob/master/MetaMaps_example_output.zip

**Comment by RxLoutre** [comment]
Alright that's perfect ! Thanks a lot !
