### ISSUE TITLE
metamaps: error while loading shared libraries: libboost_filesystem.so.1.71.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by bestweicheng** [DiltheyLab/MetaMaps#21]
metamaps mapDirectly --all -r databases/miniSeq+H/DB.fa -q input.fastq -o classification_results

@：metamaps: error while loading shared libraries: libboost_filesystem.so.1.71.0: cannot open shared object file: No such file or directory

I cant open metamaps（it is a application/x-sharedlib）so I dont know how to put this  (libboost_filesystem.so.1.71.0)

**Comment by AlexanderDilthey** [comment]
Your `LD_LIBRARY_PATH` environment variable needs to contain the path to the Boost libraries. You can check the current value via `echo $LD_LIBRARY_PATH`.
