### ISSUE TITLE
Question: will MetaMaps work to map 18S MinION reads from a pcr product? 

### ISSUE THREAD

**Issue by l-yampolsky** [DiltheyLab/MetaMaps#25]
If I use, say, SILVA 18S database as the reference?

If yes, what would be good parameters for such mapping?
Thanks!

**Comment by AlexanderDilthey** [comment]
It may work (in the sense of: not throwing an error), but the algorithm and the model were really developed for analysis of whole-genome shotgun data. I don't thing MetaMaps is the right tool for this application.
