### ISSUE TITLE
Extracting all representative and reference genomes from GenBank and put it into DB.

### ISSUE THREAD

**Issue by ms-gx** [DiltheyLab/MetaMaps#28]
I would like to make a very extensive ref. DB for MetaMaps.

Ideally I take all genomes with RefSeq category `reference genome` and `representative genome` so that I have one genome per Species.

What are your thoughts? Is this pure madness or do you think this should work on a decent compute infrastructure?

Any thoughts on how to optimize this?

**Comment by AlexanderDilthey** [comment]
I think we discussed this during our call. Feel free to re-open if any further questions arise.
