### ISSUE TITLE
Configure issue (usability)

### ISSUE THREAD

**Issue by ArnieBerg** [DiltheyLab/MetaMaps#29]
I have the same symptom as https://github.com/DiltheyLab/MetaMaps/issues/20, except I don't use conda.  I am running Ubuntu 18.04.  The configure command I use is:

./configure --with-boost=/media/analynano/Data500GB/ArnieFiles/boost_1_71_0/boost --prefix=/media/analynano/Data500GB/ArnieFiles/MetaMaps

The error lines are:

checking boost/math/distributions/binomial.hpp usability... no
checking boost/math/distributions/binomial.hpp presence... no
checking for boost/math/distributions/binomial.hpp... no

What does this error indicate?

**Comment by ArnieBerg** [comment]
Is this product still supported?  We will not be able to use this product unless issues can be resolved.

**Comment by AlexanderDilthey** [comment]
Yes, it is. I have been traveling a lot over the last weeks. Hope to get back to you early next week.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AlexanderDilthey** [comment]
Have you tried calling the configure script with

 --with-boost=/media/analynano/Data500GB/ArnieFiles/boost_1_71_0

?


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ArnieBerg** [comment]
Thanks for responding.

I did try
--with-boost=/media/analynano/Data500GB/ArnieFiles/boost_1_71_0
with the same result.  

The last lines of the output are:

checking boost/math/distributions/binomial.hpp usability... no
checking boost/math/distributions/binomial.hpp presence... no
checking for boost/math/distributions/binomial.hpp... no
configure: error: Boost Library headers not found.

**Comment by AlexanderDilthey** [comment]
Hmmm... but you confirm that /media/analynano/Data500GB/ArnieFiles/boost_1_71_0/boost/math/distributions/binomial.hpp exists on your machine?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ArnieBerg** [comment]
Yes, this is the path to binomial.hpp:
/media/analynano/Data500GB/ArnieFiles/boost_1_71_0/boost/math/distributions/binomial.hpp

**Comment by AlexanderDilthey** [comment]
I now believe the issue has to do with a missing `include` subdirectory.

One of my colleagues writes:

> Assuming boost is installed properly:
> Suppose path=folder is given, then the folder should have include, bin, and lib folders in it
> The error indicates that the config is not able to locate folder/include/boost/math/distributions/binomial.hpp

**Comment by ArnieBerg** [comment]
Yes! There was no 'include' folder in 'boost_1_71_0', so I created one and copied the 'boost' folder and all its contents into the created 'include' folder, and now configure runs without error.

**Comment by AlexanderDilthey** [comment]
Super! Thank you for your patience and your feedback!

**Comment by dportik** [comment]
Ran into the exact same issue. I installed boost (1.75.0) in a custom path did not create an `include/` folder. Running `./configure` resulted in errors. I copied the `boost/` folder into a manually created folder called `include/` and `./configure` completed without error.
