### ISSUE TITLE
Error during second step

### ISSUE THREAD

**Issue by jenniferlu717** [DiltheyLab/MetaMaps#3]
Hi, I got the following error during the second step. I'm using the downloaded miniSeq+H database 

`Outputting mappings with adjusted alignment qualities.
mashmap: src/meta/taxonomy.h:64: std::string meta::taxonomy::getFirstNonXNode(std::string): Assertion nodeID.find("x") == std::string::npos' failed.
Aborted (core dumped)`

**Command Lines:**
`mashmap mapDirectly --all -r miniSeq+H/DB.fa -q sample1.fastq -o sample1_metamaps_classification
mashmap classify --mappings sample1_metamaps_classification --DB miniSeq+H`

**Comment by AlexanderDilthey** [comment]
Hi Jennifer,
Thank you for spotting this. I've added a debug message that should reveal what's going on. Could you pull from GitHub and recompile? Alternatively you could also send me the FASTQ.

**Comment by AlexanderDilthey** [comment]
The error is not fixed, but it should print additional debug information.

Can you try a complete rebuild with 'make clean' and then 'make metamaps' (the makefile error is fixed now), and then use the metamaps command instead of mashmap? It should then print the variables 'runningNodeID' and 'nodeID'.

**Comment by jenniferlu717** [comment]
It doesn't print the values unfortunately. 

`EM round 30
 EM round 30, read << 60000 / 69799
        Log likelihood: -1.52751e+06
        Improvement: 0.985079
        Relative   : 0.999999
Outputting mappings with adjusted alignment qualities.
metamaps: src/meta/taxonomy.h:71: std::string meta::taxonomy::getFirstNonXNode(std::string): Assertion `nodeID.find("x") == std::string::npos' failed.
Aborted (core dumped)
`

>

**Comment by jenniferlu717** [comment]
It works now! Thanks :)
