### ISSUE TITLE
Doesn`t find th script named "filterLowIdentityEntities.pl"

### ISSUE THREAD

**Issue by tenlives** [DiltheyLab/MetaMaps#30]
Hello !
         Could you provide me with the script ? I couldn`t find it in you provided files ,Thank you very much!

Best wishes !

**Comment by AlexanderDilthey** [comment]
Sorry - I've added the script to the repository on GitHub. See directory `util`.

**Comment by tenlives** [comment]
@AlexanderDilthey  That`s Great ! Thank you very much ! I think the the Line 35 in the script  should  be reordered to make $DB ranks first .  I have a question that would the result of this script  be  the input of the  classify step?
