### ISSUE TITLE
Dropbox download issue

### ISSUE THREAD

**Issue by apredeus** [DiltheyLab/MetaMaps#32]
Hello, 

thank you for the tool - seems very useful. Dropbox must have reached bandwidth limit since download keeps failing. Thought I'd give you a heads-up. 

Cheers

**Comment by AlexanderDilthey** [comment]
HI @apredeus, thank you for the heads-up!

Does the problem persist? I just tried and had no issues, but this might be network- / geography-dependent...

**Comment by apredeus** [comment]
I've tried with simple download and wget and it breaks mid-download. I've had similar issues when trying to share big files with many collaborators via Dropbox - I think it exceeds the daily bandwidth of 200 Gb. 

At any rate, saving it to my Dropbox worked.
