### ISSUE TITLE
mapAgainstIndex

### ISSUE THREAD

**Issue by Mattstorey** [DiltheyLab/MetaMaps#36]
Hi.
Just wondering how and when to use the mapAgainstIndex and index commands?
Thanks,

**Comment by AlexanderDilthey** [comment]
Hi @Mattstorey,
This is how you could use the commands:

````
./mashmap index -r ref.fa -i myIndex1
./mashmap mapAgainstIndex -i myIndex1 -q test.fastq -o output
````

We don't recommend, however, using index-based mapping - it complicates the command line call scheme, and the benefits in terms out execution time are not particularly large.

**Comment by Mattstorey** [comment]
Thanks!
