### ISSUE TITLE
mapAgainstIndex frozen

### ISSUE THREAD

**Issue by schorlton** [DiltheyLab/MetaMaps#40]
I indexed miniseq and am now trying to map against my index. I am aware this is not the recommended approach, however I am trying to save some time  (#36). MetaMaps is unfortunately getting frozen at the mapping stage:
![image](https://user-images.githubusercontent.com/10245822/77274693-bad85500-6c73-11ea-8a0c-08deb4181a4b.png)

It hangs at this screen for hours at 0% CPU, 144GB RES ram. The mapDirectly function works no problem.
My index command is:
`~/Programs/MetaMaps/metamaps index -r databases/miniSeq+H/DB.fa -i metamaps_mini --mm 140 -t 30`
and it appears to succeed too.

**Comment by AlexanderDilthey** [comment]
Hi @schorlton,

This is now fixed - it was due to an error in how the multithreading was implemented.

Best

Alex
