### ISSUE TITLE
Assertion error in EM

### ISSUE THREAD

**Issue by pkonieczny** [DiltheyLab/MetaMaps#44]
I've encountered the following error while running `metamaps classify` for the very first time:
```
Starting EM...
metamaps: src/meta/fEM.h:500: void meta::doEM(const skch::Parameters&, const string&): Assertion `abs(1 - f_sum) <= 1e-3' failed.
Aborted (core dumped)
```
Not sure what to make of that.

**Comment by kebarr** [comment]
i am experiencing the same issue. any suggestions as to how to resolve?

**Comment by FabbriniMarco** [comment]
Same error here

**Comment by vmurigneu** [comment]
Same error here, metamaps v0.1

**Comment by AlexanderDilthey** [comment]
Hey @pkonieczny @kebarr @FabbriniMarco @vmurigneu,

The most likely explanation is that none of the reads in your input data could be mapped. I modified the code to show an informative error message when this situation occurs.

Best wishes

Alex
