### ISSUE TITLE
Classify is killed during EM round 0

### ISSUE THREAD

**Issue by r-follador** [DiltheyLab/MetaMaps#47]
I don't know if MetaMaps is still being maintained, but I'm currently trying out different Metagenomic analysis software.

Anyway, I'm getting following error without any further explanation during the "Classify" step (the "mapDirectly" step is working flawless):

```
>>>>>>>>>>>>>>>>>>
DB = database_plastid/MetaMaps_db/database
Mappings = TRNLa_M000197_metamaps_result
Min. reads for 'U' = 10000
Threads = 10
>>>>>>>>>>>>>>>>>>
Read taxonomy from database_plastid/MetaMaps_db/database/taxonomy -- have 9503 nodes.
Starting EM...
EM round 0
Killed
```

How can I find more information on what went wrong? It might have to do something with the size of the dataset I'm using (memory consumption?). When I'm using only 10% of the reads (and the same database, same settings), it works fine.

Any ideas?

**Comment by AlexanderDilthey** [comment]
Hey @r-follador,

This is probably due to memory issues - you could wrap your call into a `/usr/bin/time -v` and check how much RAM it consumes (alternatively, monitor RAM consumption via `top`).
