### ISSUE TITLE
Mapping step spent very long time is normal?

### ISSUE THREAD

**Issue by J-I-P** [DiltheyLab/MetaMaps#53]
Hi, everyone
I used MetaMaps to mapping, and it spent a large time. My dataset is below:
reference: databases/miniSeq+H/DB.fa
query: two_reads.fasta 
![image](https://user-images.githubusercontent.com/17896123/102678674-dc577480-41e4-11eb-8da3-61e6d42e7251.png)
maxmemory: 50
threads: 20
![image](https://user-images.githubusercontent.com/17896123/102678689-01e47e00-41e5-11eb-9a28-4876fbfd4638.png)
![image](https://user-images.githubusercontent.com/17896123/102678706-19bc0200-41e5-11eb-9c65-613ce500391c.png)
My Query is only two reads, but mapping time needs ten hours. Is it correct and normal?

Thanks for any advice on this!

**Comment by J-I-P** [comment]
Hi, I used MetaMaps to mapping, and it spent a large time. My dataset is below:
reference: databases/miniSeq+H/DB.fa
query: two_reads.fasta 
![image](https://user-images.githubusercontent.com/17896123/102678674-dc577480-41e4-11eb-8da3-61e6d42e7251.png)
maxmemory: 50
threads: 20
![image](https://user-images.githubusercontent.com/17896123/102678689-01e47e00-41e5-11eb-9a28-4876fbfd4638.png)
![image](https://user-images.githubusercontent.com/17896123/102678706-19bc0200-41e5-11eb-9c65-613ce500391c.png)
My Query is only two reads, but mapping time needs ten hours. Is it correct and normal?

**Comment by AlexanderDilthey** [comment]
Hey @J-I-P,

Indexing the database can take a substantial amount of time - when you process a file with more reads, runtime should go up sub-linearly.

Best wishes

Alex
