### ISSUE TITLE
metamaps classify error

### ISSUE THREAD

**Issue by khoriba** [DiltheyLab/MetaMaps#55]
Hi,

Metamaps classify doesn't work well.
The following error is output and dumped.

$ metamaps classify -t 5 --mappings ARs_draft_results --DB databases/miniSeq+H
>>>>>>>>>>>>>>>>>>
DB = databases/miniSeq+H
Mappings = ARs_draft_results
Min. reads for 'U' = 10000
Threads = 5
>>>>>>>>>>>>>>>>>>
metamaps: src/meta/fEM.h:402: std::map<std::__cxx11::basic_string<char>, long unsigned int> meta::getMappingStats(std::__cxx11::string): Assertion `statsStream.is_open()' failed.

**Comment by AlexanderDilthey** [comment]
Referencing https://github.com/DiltheyLab/MetaMaps/issues/68.
