### ISSUE TITLE
What is the miniSeq+H based on (when was the refseq genomes downloaded)?

### ISSUE THREAD

**Issue by dawnmy** [DiltheyLab/MetaMaps#56]
Thank you for such an amazing tool. I would like to know when was the miniSeq+H database (https://www.dropbox.com/s/6p9o42yufx2vkae/miniSeq%2BH.tar.gz?dl=0) built? Which version of RefSeq is it based on  (When was it downloaded)?

**Comment by anuradhawick** [comment]
@AlexanderDilthey I also have the same question. It would be amazing if you can share some information.

Thanks
Anuradha

**Comment by AlexanderDilthey** [comment]
Dear @dawnmy and @anuradhawick,

Unfortunately I do not have a download date or a specific RefSeq version number for the miniSeq+H database. If this is for ensuring reproducibility in the context of a publication, you could store the utilized file on e.g. OSF. Sorry I have no better answer for you!

Best wishes

Alex
