### ISSUE TITLE
Error when using mapDirectly

### ISSUE THREAD

**Issue by m-crown** [DiltheyLab/MetaMaps#58]
Hi, 

When using the following command (FASTQ and outdir paths changed for brevity): 

` ./metamaps mapDirectly --all -r databases/miniSeq+H/DB.fa -q /path/to/fastq -o /path/to/outdir --maxmemory 40 -t 10`

I received the following error upon what appears to have been successful completion of the command (but no files have been written): 

`Index construction DONE, wrote 6 files. 
metamaps: src/map/mapWrap.h:40: void mapWrap::unifyFiles(std::__cxx11::string, const skch::Parameters&, std::vector<std::__cxx11::basic_string<char> >, std::vector<std::__cxx11::basic_string<char> >): Assertion combinedOutput.is_open()' failed. 
Aborted (core dumped)`

The program exited with code 134. Could anyone offer any insight into the cause of this problem? 

Thanks, 

Matt

**Comment by AlexanderDilthey** [comment]
Hi @m-crown,

This error occurs when the file that will contain the combined output of the mapping process cannot be opened - is it possible there is a disk space or permission issue with your specific output location?

Best wishes

Alex
