### ISSUE TITLE
percentage identity and coverage info - misclassification

### ISSUE THREAD

**Issue by molbio7** [DiltheyLab/MetaMaps#61]
Hi @AlexanderDilthey,
We have been getting misclassifications for a lot of the reads and if we pull out those misclassified reads and blast it against ncbi, those reads give no hits but a taxonomy has been assigned against those reads when using metamaps.
Happy to send you a dataset if you wish to have a look please.

**Comment by AlexanderDilthey** [comment]
Hi @molbio7 ,

Thank you for your message!

Unless we release a second version of MetaMaps, we will not modify the core classification algorithm.

The could try to play around with the parameter for window size (parameter `-w` for the mapping step) or kmer size (parameter `-k` for the mapping step) and see whether this influences the rate of false-positives.

Best wishes

Alex
