### ISSUE TITLE
Build reference database from GTDB

### ISSUE THREAD

**Issue by aditi48n** [DiltheyLab/MetaMaps#62]
Hello @AlexanderDilthey . I wanted to build my own reference database from GTDB. Would that be possible using the Perl script provided or is there a different way to do it? 

Thanks.

**Comment by AlexanderDilthey** [comment]
Hi @aditi48n,

I would recommend trying this workflow: https://github.com/DiltheyLab/MetaMaps/issues/5#issuecomment-414301437

Best wishes

Alex
