### ISSUE TITLE
Cannot open DB.fa for size determination

### ISSUE THREAD

**Issue by wangtao0000** [DiltheyLab/MetaMaps#64]
Hi,
When i run the command "metamaps mapDirectly --all -r databases/miniSeq+H/DB.fa -q Multiple_lr_1.fastq -o classification_results", it has an error like this:
Cannot open databases/miniSeq+H/DB.fa for size determination.

Looking forward for your answer, thanks.

**Comment by AlexanderDilthey** [comment]
Hi @wangtao0000,

I assume the file `databases/miniSeq+H/DB.fa` may not exist relative to the working directory you are in?

Best wishes

Alex
