### ISSUE TITLE
Presence of carrier return line endings in Perl utilities

### ISSUE THREAD

**Issue by nsmro** [DiltheyLab/MetaMaps#66]
Hi,

Just to let you know that when I try to run any of the perl utilities provided with metamaps on a ubuntu system
This command:
```bash
./DBinfo.pl
```
will return
`/DBinfo.pl: /usr/bin/perl^M: bad interpreter: No such file or directory`
Because of CR characters.

**Comment by AlexanderDilthey** [comment]
Thank you, this is now fixed!
