### ISSUE TITLE
Can a database be added via shared memory?

### ISSUE THREAD

**Issue by jsonProgram** [DiltheyLab/MetaMaps#67]
Loading the database is slow...
Any ideas to speed up this step?
For example shared memory method

**Comment by AlexanderDilthey** [comment]
Hi @jsonProgram,

We do currently not support shared memory, but you can try to build the index and then store it to disk, like so (using the undocumented `mapAgainstIndex` command):

```
./metamaps index -i databases/miniSeq+H/DB.short.idx -r databases/miniSeq+H/DB.short.fa
./metamaps mapAgainstIndex --all -i databases/miniSeq+H/DB.short.idx -q test.fastq -o classification_results
´´´

**Comment by AlexanderDilthey** [comment]
Also, there was a bug in the code that implemented mapping against a pre-built index; if you want to try this feature, do a fresh pull and re-compile MetaMaps.

-A
