### ISSUE TITLE
Running problems of metamaps: Assertion `statsStream.is_open()' failed.

### ISSUE THREAD

**Issue by wangqi0000** [DiltheyLab/MetaMaps#68]
Hi everyone and thank you for the time you'll spend reading this issue.
There is a problem when running metamaps and I don't know how to solve it. The command, generated files, and errors are shown below.

**Command used:**
```
metamaps mapDirectly --all -r ../databases/miniSeq+H/DB.fa -q /fs/ess/PCON0022/qiuqinwu/wangqi/pbsim/simulated_data/multiple-species/Multiple_lr_4.fastq -o classification_results_4 --maxmemory 250
metamaps classify --mappings classification_results_4 --DB ../databases/miniSeq+H
```

**Files generated using above command:**
![image](https://user-images.githubusercontent.com/85976600/194977518-9ef1802a-a2ef-4303-ad92-c5d03fc5ed2f.png)

**Error:**
metamaps: src/meta/fEM.h:402: std::map<std::__cxx11::basic_string<char>, long unsigned int> meta::getMappingStats(std::__cxx11::string): Assertion `statsStream.is_open()' failed.
/var/spool/slurmd/job12902838/slurm_script: line 17: 166525 Aborted                 (core dumped) metamaps classify --mappings classification_results_5 --DB ../databases/miniSeq+H

**Comment by AlexanderDilthey** [comment]
Hi @wangqi0000,

This error occurs when the file `classification_results_4.meta` is not present. This is generated automatically at the end of the mapping process, so perhaps mapping did not complete successfully in your case?

I have added an improved error message that makes more clear what the underlying error is.

Best wishes

Alex
