### ISSUE TITLE
Error in classify step

### ISSUE THREAD

**Issue by nllg** [DiltheyLab/MetaMaps#7]
Hello,
I am testing your tool and I get this error when I run: 
./metamaps classify --mappings classification_results.1 --DB databases/miniSeq+H

The error is as follows:
Min. reads for 'U' = 10000
>>>>>>>>>>>>>>>>>>
metamaps: src/meta/fEM.h:350: std::map<std::__cxx11::basic_string<char>, long unsigned int> meta::getMappingStats(std::__cxx11::string): Assertion `statsStream.is_open()' failed.
****

Thank you in advance!

Nathaly

**Comment by AlexanderDilthey** [comment]
Hi Nathaly,

You should probably use `--mappings classification_results` instead of `--mappings classification_results.1`, unless you explicitly specified `-o classification_results.1` when mapping.

If the output file `classification_results` (i.e. without the `.1`) is not present, then something went wrong with the mapping step.

Best,

Alex

**Comment by nllg** [comment]
ok, then it might be that the mapping step didn't work out. I will run the mapping step again.
Thank you very much!
Cheers,
Nathaly

**Comment by nllg** [comment]
Hi Alex,

I ran the mapping step again. I used the following command:
metamaps mapDirectly --all -r /databases/miniSeq+H/DB.fa -q reads.fasta -o classification_results

The program ran for 8 days and once again,  the output was classification_results.1
As expected, when I ran the classify step, I got the same error as before:

Min. reads for 'U' = 10000

metamaps: src/meta/fEM.h:350: std::map<std::__cxx11::basic_string, long unsigned int> meta::getMappingStats(std::__cxx11::string): Assertion `statsStream.is_open()' failed.

Do you have any suggestions?

Thank you very much,

Nathaly

**Comment by AlexanderDilthey** [comment]
Hi Nathaly,
Can you post the classify command you used?
Thanks,
Alex

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by AlexanderDilthey** [comment]
Thank you! If the file without the .1 doesn’t exist, mapping has failed. Can you capture exit code and output with /usr/bin/time -v ... &> output.txt, where you substitute the ‚...‘ with your mapping command?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
