### ISSUE TITLE
MetaMaps no longer supported?

### ISSUE THREAD

**Issue by julianzaugg** [DiltheyLab/MetaMaps#70]
Hi @AlexanderDilthey. Can you confirm whether MetaMaps is no longer supported? Going by the number of and age of unresolved issues, I assume this is the case?

**Comment by AlexanderDilthey** [comment]
Hi @julianzaugg,

During the Covid-19 pandemic, we did not have a lot of time for supporting MetaMaps - I hope this is getting a bit better now.

Best wishes

Alexander
