### ISSUE TITLE
Symbol lookup error

### ISSUE THREAD

**Issue by marceaf23** [DiltheyLab/MetaMaps#9]
I am getting this error when running metamaps and can't figure out why. 
<img width="1430" alt="screen shot 2018-11-28 at 11 04 00 am" src="https://user-images.githubusercontent.com/6750641/49164635-82359f00-f2fd-11e8-98e1-96706bf0fb78.png">

**Comment by AlexanderDilthey** [comment]
This somehow relates to an issue with the Boost libraries. Which version of Boost do you use? Can you post the generated makefile?

Thanks,

Alex

________________________________
Von: marceaf23 <notifications@github.com>
Gesendet: Mittwoch, 28. November 2018 17:05
An: DiltheyLab/MetaMaps
Cc: Subscribed
Betreff: [DiltheyLab/MetaMaps] Symbol lookup error (#9)


I am getting this error when running metamaps and can't figure out why.
[screen shot 2018-11-28 at 11 04 00 am]<https://user-images.githubusercontent.com/6750641/49164635-82359f00-f2fd-11e8-98e1-96706bf0fb78.png>

**Comment by marceaf23** [comment]
<img width="1433" alt="screen shot 2018-11-28 at 1 49 52 pm" src="https://user-images.githubusercontent.com/6750641/49174520-84572800-f314-11e8-8319-a05ed25f5360.png">
Here is the makefile generated. I am using boost 1.58

**Comment by marceaf23** [comment]
You were right, it was a problem with my Boost path. Fixed it. Thank you!
